import { NgModule     } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatProgressSpinnerModule,
         MatFormFieldModule,
         MatInputModule,
         MatGridListModule,
         MatToolbarModule,
         MatSelectModule,
         MatSnackBarModule,
         MatIconModule,
         MatStepperModule,
         MatDividerModule,
         MatRadioModule,
         MatSidenavModule,
         MatListModule,
         MatAutocompleteModule,
         MatProgressBarModule,
         MatCardModule,
         MatExpansionModule,
         MatButtonModule,
         MatTableModule,
         MatTabsModule} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
  CommonModule,
  MatTableModule,
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatGridListModule,
  MatToolbarModule,
  MatSelectModule,
  MatSnackBarModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatStepperModule,
  MatDividerModule,
  MatRadioModule,
  MatSidenavModule,
  MatListModule,
  MatAutocompleteModule,
  MatProgressBarModule,
  MatCardModule,
  MatExpansionModule,
  MatTabsModule
  ],
  exports: [
  MatTableModule,
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatGridListModule,
  MatToolbarModule,
  MatSelectModule,
  MatSnackBarModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatStepperModule,
  MatDividerModule,
  MatRadioModule,
  MatSidenavModule,
  MatListModule,
  MatAutocompleteModule,
  MatProgressBarModule,
  MatCardModule,
  MatExpansionModule,
  MatTabsModule
  ]
})
export class MaterialModule { }
